# chrono @ 2021-03

# kubernetes pod yaml for cpp note
# you could run it in k8s/minikube/kind/...

# kubectl apply  -f cpp-note-pod.yml
# kubectl delete -f cpp-note-pod.yml
#
# kubectl get pods
# kubectl exec -it k8s-cpp-note -- bash
# kubectl attach -it k8s-cpp-note

apiVersion: v1
kind: Pod

metadata:
    name: k8s-cpp-note
    labels:
        author: chrono
        lang: cpp
        env: study

spec:

    containers:

    - name: cpp-note
      image: chronolaw/cpp_note:gcc7
      #image: chronolaw/cpp_note:gcc10
      workingDir: /root/cpp_note

      # exec or attach into this container
      stdin: true
      tty: true

